version: '3.8'
services:
  ship-classifier:
    image: as135/ship-classifier
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    volumes:
      - ./artifacts:/app/artifacts
